default:
  tagFilter:
    regex: ^v?\d+(\.\d+){0,2}$
images:
  - from: registry.k8s.io/ingress-nginx/kube-webhook-certgen
    to: docker.io/k8smirror/ingress-nginx-kube-webhook-certgen
    tagFilter:
      regex: ^v.*$
  - from: registry.k8s.io/ingress-nginx/opentelemetry
    to: docker.io/k8smirror/ingress-nginx-opentelemetry
    tagFilter:
      regex: ^v\w+-\w+$
  - from: registry.k8s.io/defaultbackend-amd64
    to: docker.io/k8smirror/defaultbackend-amd64
    tagFilter:
      regex: ^.*$
  - from: registry.k8s.io/ingress-nginx/controller
    to: docker.io/k8smirror/ingress-nginx-controller
  - from: registry.k8s.io/kube-state-metrics/kube-state-metrics
    to: docker.io/k8smirror/kube-state-metrics
