apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: sync-images

configMapGenerator:
  - name: image-porter-config
    files:
      - config/config.yaml

secretGenerator:
  - name: image-porter-docker-config
    files:
      - docker/config.json

resources:
  - namespace.yaml
  - cronjob.yaml
